//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Paranoia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        public static string AppMenuText {
            get {
                return ResourceManager.GetString("AppMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide ribbon. Click on the application bar at the top to display it..
        /// </summary>
        public static string AutoHideRibbonDescription {
            get {
                return ResourceManager.GetString("AutoHideRibbonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-hide ribbon.
        /// </summary>
        public static string AutoHideRibbonTitle {
            get {
                return ResourceManager.GetString("AutoHideRibbonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseCommandText {
            get {
                return ResourceManager.GetString("CloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseTooltip {
            get {
                return ResourceManager.GetString("CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not a property..
        /// </summary>
        public static string ExpressionNotProperty {
            get {
                return ResourceManager.GetString("ExpressionNotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string MaximizeCommandText {
            get {
                return ResourceManager.GetString("MaximizeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string MaximizeTooltip {
            get {
                return ResourceManager.GetString("MaximizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeCommandText {
            get {
                return ResourceManager.GetString("MinimizeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeTooltip {
            get {
                return ResourceManager.GetString("MinimizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access member in Expression..
        /// </summary>
        public static string NotMemberAccessExpression {
            get {
                return ResourceManager.GetString("NotMemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Down.
        /// </summary>
        public static string RestoreDownCommandText {
            get {
                return ResourceManager.GetString("RestoreDownCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Down.
        /// </summary>
        public static string RestoreDownTooltip {
            get {
                return ResourceManager.GetString("RestoreDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbon Visibility Options.
        /// </summary>
        public static string RibbonOptionsText {
            get {
                return ResourceManager.GetString("RibbonOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbon Visibility Options.
        /// </summary>
        public static string RibbonOptionsTooltip {
            get {
                return ResourceManager.GetString("RibbonOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ribbon.
        /// </summary>
        public static string ShowRibbonTooltip {
            get {
                return ResourceManager.GetString("ShowRibbonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently displays the ribbons tabs and commands..
        /// </summary>
        public static string ShowTabsAndCommandsDescription {
            get {
                return ResourceManager.GetString("ShowTabsAndCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs and commands.
        /// </summary>
        public static string ShowTabsAndCommandsTitle {
            get {
                return ResourceManager.GetString("ShowTabsAndCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays only the tabs. Click on a tab to displays its commands..
        /// </summary>
        public static string ShowTabsDescription {
            get {
                return ResourceManager.GetString("ShowTabsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs.
        /// </summary>
        public static string ShowTabsTitle {
            get {
                return ResourceManager.GetString("ShowTabsTitle", resourceCulture);
            }
        }
    }
}
