//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PublicKey { get; set; }
        public string EmailAddress { get; set; }
        public int IdentityId { get; set; }
        public byte RequestStatus { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
