//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailboxFlag
    {
        public int Id { get; set; }
        public int MailboxId { get; set; }
        public string Name { get; set; }
    
        public virtual Mailbox Mailbox { get; set; }
    }
}
