//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        public Mailbox()
        {
            this.Delimiter = "/";
            this.Messages = new HashSet<Message>();
            this.MailboxFlags = new HashSet<MailboxFlag>();
        }
    
        public int Id { get; set; }
        public int ImapAccountId { get; set; }
        public string Fullname { get; set; }
        public string Delimiter { get; set; }
        public int MessageCount { get; set; }
        public int UnseenCount { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ImapAccount ImapAccount { get; set; }
        public virtual ICollection<MailboxFlag> MailboxFlags { get; set; }
    }
}
