//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageFlags = new HashSet<MessageFlag>();
        }
    
        public int Id { get; set; }
        public int MailboxId { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public int Size { get; set; }
    
        public virtual Mailbox Mailbox { get; set; }
        public virtual ICollection<MessageFlag> MessageFlags { get; set; }
    }
}
