//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmtpAccount
    {
        public int Id { get; set; }
        public string Host { get; set; }
        public short Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public short Security { get; set; }
    }
}
