//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Crystalbyte.Paranoia { // 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class clientConfig {
    
        private clientConfigEmailProvider[] emailProviderField;
    
        private string versionField;
    
        /// <remarks/>
        [XmlElement("emailProvider", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public clientConfigEmailProvider[] emailProvider {
            get {
                return this.emailProviderField;
            }
            set {
                this.emailProviderField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class clientConfigEmailProvider {
    
        private string domainField;
    
        private string displayNameField;
    
        private string displayShortNameField;
    
        private clientConfigEmailProviderIncomingServer[] incomingServerField;
    
        private clientConfigEmailProviderOutgoingServer[] outgoingServerField;
    
        private clientConfigEmailProviderDocumentation[] documentationField;
    
        private string idField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string displayShortName {
            get {
                return this.displayShortNameField;
            }
            set {
                this.displayShortNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("incomingServer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public clientConfigEmailProviderIncomingServer[] incomingServer {
            get {
                return this.incomingServerField;
            }
            set {
                this.incomingServerField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("outgoingServer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public clientConfigEmailProviderOutgoingServer[] outgoingServer {
            get {
                return this.outgoingServerField;
            }
            set {
                this.outgoingServerField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("documentation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public clientConfigEmailProviderDocumentation[] documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class clientConfigEmailProviderIncomingServer {
    
        private string hostnameField;
    
        private string portField;
    
        private string socketTypeField;
    
        private string authenticationField;
    
        private string usernameField;
    
        private string typeField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string socketType {
            get {
                return this.socketTypeField;
            }
            set {
                this.socketTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class clientConfigEmailProviderOutgoingServer {
    
        private string hostnameField;
    
        private string portField;
    
        private string socketTypeField;
    
        private string authenticationField;
    
        private string usernameField;
    
        private string typeField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string socketType {
            get {
                return this.socketTypeField;
            }
            set {
                this.socketTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class clientConfigEmailProviderDocumentation {
    
        private clientConfigEmailProviderDocumentationDescr[] descrField;
    
        private string urlField;
    
        /// <remarks/>
        [XmlElement("descr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public clientConfigEmailProviderDocumentationDescr[] descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class clientConfigEmailProviderDocumentationDescr {
    
        private string langField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
    
        private clientConfig[] itemsField;
    
        /// <remarks/>
        [XmlElement("clientConfig")]
        public clientConfig[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}