//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Paranoia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type in your email address ....
        /// </summary>
        public static string IdentityEmailAddressWatermark {
            get {
                return ResourceManager.GetString("IdentityEmailAddressWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to get you started, it is required to create a unique identity..
        /// </summary>
        public static string IdentityHeaderText {
            get {
                return ResourceManager.GetString("IdentityHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type in your name ....
        /// </summary>
        public static string IdentityNameWatermark {
            get {
                return ResourceManager.GetString("IdentityNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can attach some notes here ....
        /// </summary>
        public static string IdentityNotesWatermark {
            get {
                return ResourceManager.GetString("IdentityNotesWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following properties are private and will be only visible to you..
        /// </summary>
        public static string IdentityPrivateDescription {
            get {
                return ResourceManager.GetString("IdentityPrivateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These properties are public and will be visible to the people you communicate with..
        /// </summary>
        public static string IdentityPublicDescription {
            get {
                return ResourceManager.GetString("IdentityPublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Identity.
        /// </summary>
        public static string IdentityTitle {
            get {
                return ResourceManager.GetString("IdentityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered is not a valid email address..
        /// </summary>
        public static string InvalidEmailFormatErrorText {
            get {
                return ResourceManager.GetString("InvalidEmailFormatErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must not exceed 64 characters..
        /// </summary>
        public static string MaxStringLength64ErrorText {
            get {
                return ResourceManager.GetString("MaxStringLength64ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        public static string NameRequiredErrorText {
            get {
                return ResourceManager.GetString("NameRequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must not be empty..
        /// </summary>
        public static string NullOrEmptyErrorText {
            get {
                return ResourceManager.GetString("NullOrEmptyErrorText", resourceCulture);
            }
        }
    }
}
