//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Paranoia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Paranoia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettingsTitle {
            get {
                return ResourceManager.GetString("AccountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Images.
        /// </summary>
        public static string AllImages {
            get {
                return ResourceManager.GetString("AllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllMailbox {
            get {
                return ResourceManager.GetString("AllMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearence.
        /// </summary>
        public static string Appearence {
            get {
                return ResourceManager.GetString("Appearence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystalbyte Paranoia.
        /// </summary>
        public static string ApplicationLongName {
            get {
                return ResourceManager.GetString("ApplicationLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranoia.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranoia is a secure mail application..
        /// </summary>
        public static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paranoia.
        /// </summary>
        public static string AssemblyTitle {
            get {
                return ResourceManager.GetString("AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification failed..
        /// </summary>
        public static string AuthentificationFailed {
            get {
                return ResourceManager.GetString("AuthentificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox is bound..
        /// </summary>
        public static string BindingNotice {
            get {
                return ResourceManager.GetString("BindingNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bcc.
        /// </summary>
        public static string BlindCarbonCopies {
            get {
                return ResourceManager.GetString("BlindCarbonCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protect your privacy all external content from this source has been blocked. .
        /// </summary>
        public static string BlockedContentDescription {
            get {
                return ResourceManager.GetString("BlockedContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BoldGlyph {
            get {
                return ResourceManager.GetString("BoldGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        public static string CarbonCopies {
            get {
                return ResourceManager.GetString("CarbonCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page certificate for domain &apos;{0}&apos; is not valid..
        /// </summary>
        public static string CertificateErrorTemplate {
            get {
                return ResourceManager.GetString("CertificateErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server challenge headers are missing or corrupt..
        /// </summary>
        public static string ChallengeCorruptException {
            get {
                return ResourceManager.GetString("ChallengeCorruptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string ComposeMessage {
            get {
                return ResourceManager.GetString("ComposeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Message.
        /// </summary>
        public static string ComposeMessagePageTitle {
            get {
                return ResourceManager.GetString("ComposeMessagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content host node missing from template..
        /// </summary>
        public static string ContentHostMissingException {
            get {
                return ResourceManager.GetString("ContentHostMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string CreateContactTitle {
            get {
                return ResourceManager.GetString("CreateContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a secure password. 
        ///This password will then be used to encrypt all security critical data used by this application, without it you will lose all access to your encrypted data..
        /// </summary>
        public static string CreateKeyPageDescription {
            get {
                return ResourceManager.GetString("CreateKeyPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your password wisely because we will not be able to recover any lost passwords due to the simple fact that we do not store them anywhere. Furthermore, changing the password is not possible.
        ///Once your password is lost you&apos;re screwed..
        /// </summary>
        public static string CreateKeyPageWarning {
            get {
                return ResourceManager.GetString("CreateKeyPageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Step.
        /// </summary>
        public static string CreateKeyTitle {
            get {
                return ResourceManager.GetString("CreateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the mailbox to create..
        /// </summary>
        public static string CreateMailboxDescription {
            get {
                return ResourceManager.GetString("CreateMailboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mailbox.
        /// </summary>
        public static string CreateMailboxTitle {
            get {
                return ResourceManager.GetString("CreateMailboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method was called on an invalid thread..
        /// </summary>
        public static string CrossThreadException {
            get {
                return ResourceManager.GetString("CrossThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database image not found..
        /// </summary>
        public static string DatabaseImageNotFound {
            get {
                return ResourceManager.GetString("DatabaseImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeclaringType of table property must not be null..
        /// </summary>
        public static string DeclaringTypeNull {
            get {
                return ResourceManager.GetString("DeclaringTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        public static string DeleteAccountQuestion {
            get {
                return ResourceManager.GetString("DeleteAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entf.
        /// </summary>
        public static string DeleteGesture {
            get {
                return ResourceManager.GetString("DeleteGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect my settings automagically..
        /// </summary>
        public static string DetectAutomagically {
            get {
                return ResourceManager.GetString("DetectAutomagically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting server settings ....
        /// </summary>
        public static string DetectSettings {
            get {
                return ResourceManager.GetString("DetectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string DraftMailbox {
            get {
                return ResourceManager.GetString("DraftMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string EncryptionProtocol {
            get {
                return ResourceManager.GetString("EncryptionProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t bother, I will enter my settings manually..
        /// </summary>
        public static string EnterManually {
            get {
                return ResourceManager.GetString("EnterManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit (TLS).
        /// </summary>
        public static string Explicit {
            get {
                return ResourceManager.GetString("Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not a property..
        /// </summary>
        public static string ExpressionNotProperty {
            get {
                return ResourceManager.GetString("ExpressionNotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching available mailboxes ....
        /// </summary>
        public static string FetchingMailboxes {
            get {
                return ResourceManager.GetString("FetchingMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markings.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + F.
        /// </summary>
        public static string ForwardGesture {
            get {
                return ResourceManager.GetString("ForwardGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name and e-mail address are public and will be shared with the people you communicate with..
        /// </summary>
        public static string GeneralSettingsDescription {
            get {
                return ResourceManager.GetString("GeneralSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralSettingsTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Files.
        /// </summary>
        public static string GifFiles {
            get {
                return ResourceManager.GetString("GifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string HideUnsubscribedMailboxes {
            get {
                return ResourceManager.GetString("HideUnsubscribedMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting Color.
        /// </summary>
        public static string HighlightingColor {
            get {
                return ResourceManager.GetString("HighlightingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On {0}, {1} wrote:.
        /// </summary>
        public static string HtmlResponseHeader {
            get {
                return ResourceManager.GetString("HtmlResponseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not support the IDLE extension..
        /// </summary>
        public static string IdleCommandNotSupported {
            get {
                return ResourceManager.GetString("IdleCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP.
        /// </summary>
        public static string Imap {
            get {
                return ResourceManager.GetString("Imap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ImapHost {
            get {
                return ResourceManager.GetString("ImapHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit (SSL).
        /// </summary>
        public static string Implicit {
            get {
                return ResourceManager.GetString("Implicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string InboxMailbox {
            get {
                return ResourceManager.GetString("InboxMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the address of the link to insert..
        /// </summary>
        public static string InsertLinkDescription {
            get {
                return ResourceManager.GetString("InsertLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Link.
        /// </summary>
        public static string InsertLinkTitle {
            get {
                return ResourceManager.GetString("InsertLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is now your default account..
        /// </summary>
        public static string IsDefaultAccount {
            get {
                return ResourceManager.GetString("IsDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default..
        /// </summary>
        public static string IsNotDefaultAccount {
            get {
                return ResourceManager.GetString("IsNotDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG Files.
        /// </summary>
        public static string JpgFiles {
            get {
                return ResourceManager.GetString("JpgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        public static string JunkMailbox {
            get {
                return ResourceManager.GetString("JunkMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string MailAddress {
            get {
                return ResourceManager.GetString("MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current mailbox is not assigned. 
        ///Please select a corresponding IMAP folder to synchronize..
        /// </summary>
        public static string MailboxAssignmentDescription {
            get {
                return ResourceManager.GetString("MailboxAssignmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes.
        /// </summary>
        public static string Mailboxes {
            get {
                return ResourceManager.GetString("Mailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store copies of sent messages inside the following mailbox..
        /// </summary>
        public static string MailboxSettingsCopy {
            get {
                return ResourceManager.GetString("MailboxSettingsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mailboxes to be used for storing deleted messages, drafts and junk mail..
        /// </summary>
        public static string MailboxSettingsDescription {
            get {
                return ResourceManager.GetString("MailboxSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not store copies of sent messages..
        /// </summary>
        public static string MailboxSettingsNoCopy {
            get {
                return ResourceManager.GetString("MailboxSettingsNoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Settings.
        /// </summary>
        public static string MailboxSettingsTitle {
            get {
                return ResourceManager.GetString("MailboxSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star message(s).
        /// </summary>
        public static string MarkAsFlagged {
            get {
                return ResourceManager.GetString("MarkAsFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove star from message(s).
        /// </summary>
        public static string MarkAsNotFlagged {
            get {
                return ResourceManager.GetString("MarkAsNotFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark message(s) as unread.
        /// </summary>
        public static string MarkAsNotSeen {
            get {
                return ResourceManager.GetString("MarkAsNotSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read message(s).
        /// </summary>
        public static string MarkAsSeen {
            get {
                return ResourceManager.GetString("MarkAsSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Message ....
        /// </summary>
        public static string MessageDownload {
            get {
                return ResourceManager.GetString("MessageDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested message could not be found..
        /// </summary>
        public static string MessageNotFoundException {
            get {
                return ResourceManager.GetString("MessageNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesTitle {
            get {
                return ResourceManager.GetString("MessagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is missing from type {0}..
        /// </summary>
        public static string MissingKeyTemplate {
            get {
                return ResourceManager.GetString("MissingKeyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mime data for id &apos;{0}&apos; has been found..
        /// </summary>
        public static string MissingMimeTemplate {
            get {
                return ResourceManager.GetString("MissingMimeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature with path &apos;{0}&apos; was not found..
        /// </summary>
        public static string MissingSignatureTemplate {
            get {
                return ResourceManager.GetString("MissingSignatureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no trash folder defined..
        /// </summary>
        public static string MissingTrashFolderException {
            get {
                return ResourceManager.GetString("MissingTrashFolderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to &apos;{0}&apos;..
        /// </summary>
        public static string NavigationInfoTemplate {
            get {
                return ResourceManager.GetString("NavigationInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + N.
        /// </summary>
        public static string NewMailboxGesture {
            get {
                return ResourceManager.GetString("NewMailboxGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connectivity, please check your internet connection..
        /// </summary>
        public static string NoConnectivity {
            get {
                return ResourceManager.GetString("NoConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s lonely in here :(.
        /// </summary>
        public static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to send ....
        /// </summary>
        public static string NothingToSend {
            get {
                return ResourceManager.GetString("NothingToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not access a member..
        /// </summary>
        public static string NotMemberAccessExpression {
            get {
                return ResourceManager.GetString("NotMemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; scheme is not supported..
        /// </summary>
        public static string NotSupportedSchemeTemplate {
            get {
                return ResourceManager.GetString("NotSupportedSchemeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbox.
        /// </summary>
        public static string Outbox {
            get {
                return ResourceManager.GetString("Outbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Files.
        /// </summary>
        public static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying the mozilla configuration database ....
        /// </summary>
        public static string QueryingMozillaDatabase {
            get {
                return ResourceManager.GetString("QueryingMozillaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying mx records ....
        /// </summary>
        public static string QueryingMxRecords {
            get {
                return ResourceManager.GetString("QueryingMxRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        public static string RefreshGesture {
            get {
                return ResourceManager.GetString("RefreshGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing public keys for contacts ....
        /// </summary>
        public static string RefreshingPublicKeysStatus {
            get {
                return ResourceManager.GetString("RefreshingPublicKeysStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Keys.
        /// </summary>
        public static string RegisterKeyTitle {
            get {
                return ResourceManager.GetString("RegisterKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove binding.
        /// </summary>
        public static string RemoveMailboxBinding {
            get {
                return ResourceManager.GetString("RemoveMailboxBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render process has terminated with status code &apos;{0}&apos;..
        /// </summary>
        public static string RenderProcessTerminatedTemplate {
            get {
                return ResourceManager.GetString("RenderProcessTerminatedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply All.
        /// </summary>
        public static string ReplyAll {
            get {
                return ResourceManager.GetString("ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + R.
        /// </summary>
        public static string ReplyGesture {
            get {
                return ResourceManager.GetString("ReplyGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; was not found in assembly &apos;{1}&apos;..
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting &apos;{0}&apos;..
        /// </summary>
        public static string ResourceRequestTemplate {
            get {
                return ResourceManager.GetString("ResourceRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Down.
        /// </summary>
        public static string RestoreDown {
            get {
                return ResourceManager.GetString("RestoreDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + R.
        /// </summary>
        public static string RestoreGesture {
            get {
                return ResourceManager.GetString("RestoreGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and promise not to lose my password, ever!.
        /// </summary>
        public static string RiskStatement {
            get {
                return ResourceManager.GetString("RiskStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As ....
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search (Ctrl+Q).
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string SentMailbox {
            get {
                return ResourceManager.GetString("SentMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings are required to access your incoming and outgoing mail servers.
        ///Access protocols are currently limited to the IMAP (Internet Message Access Protocol) and the SMTP (Simple Mail Transfer Protocol) protocols..
        /// </summary>
        public static string ServerSettingsDescription {
            get {
                return ResourceManager.GetString("ServerSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Server Settings.
        /// </summary>
        public static string ServerSettingsTitle {
            get {
                return ResourceManager.GetString("ServerSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not filter by contact.
        /// </summary>
        public static string ShowAllMessages {
            get {
                return ResourceManager.GetString("ShowAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Subscriptions.
        /// </summary>
        public static string ShowUnsubscribedMailboxes {
            get {
                return ResourceManager.GetString("ShowUnsubscribedMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file containing the default signature text for this account..
        /// </summary>
        public static string SignatureDescription {
            get {
                return ResourceManager.GetString("SignatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Settings.
        /// </summary>
        public static string SignatureTitle {
            get {
                return ResourceManager.GetString("SignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        public static string Smtp {
            get {
                return ResourceManager.GetString("Smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SmtpHost {
            get {
                return ResourceManager.GetString("SmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different credentials for outgoing mails..
        /// </summary>
        public static string SmtpRequiresOwnCredentials {
            get {
                return ResourceManager.GetString("SmtpRequiresOwnCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Server Settings (SMTP).
        /// </summary>
        public static string SmtpSettingsTitle {
            get {
                return ResourceManager.GetString("SmtpSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Message from {0}.
        /// </summary>
        public static string SubjectTemplate {
            get {
                return ResourceManager.GetString("SubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing mailboxes .....
        /// </summary>
        public static string SyncMailboxesStatus {
            get {
                return ResourceManager.GetString("SyncMailboxesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connectivity ....
        /// </summary>
        public static string TestingConnectivityStatus {
            get {
                return ResourceManager.GetString("TestingConnectivityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing IMAP settings ....
        /// </summary>
        public static string TestingImapStatus {
            get {
                return ResourceManager.GetString("TestingImapStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing SMTP settings ....
        /// </summary>
        public static string TestingSmtpStatus {
            get {
                return ResourceManager.GetString("TestingSmtpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tests completed successfully..
        /// </summary>
        public static string TestsCompletedSuccessfully {
            get {
                return ResourceManager.GetString("TestsCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Settings.
        /// </summary>
        public static string TestSettings {
            get {
                return ResourceManager.GetString("TestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string TrashMailbox {
            get {
                return ResourceManager.GetString("TrashMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not supported by the database..
        /// </summary>
        public static string TypeNotSupportedTemplate {
            get {
                return ResourceManager.GetString("TypeNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unseen.
        /// </summary>
        public static string Unseen {
            get {
                return ResourceManager.GetString("Unseen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate using IMAP credentials..
        /// </summary>
        public static string UseImapCredentials {
            get {
                return ResourceManager.GetString("UseImapCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
